### PR TITLE
created delete function pages and uploading pages

### PR DESCRIPTION
**Pull request by furkanozturk218**
created delete function pages and uploading pages

### CODE REVIEW

**Review by ayshe86 — APPROVED** [review]
well done

**Review by burAQyilmaz — APPROVED** [review]
yes good job

**Review by burAQyilmaz — APPROVED** [review]
bad job

**Review by burAQyilmaz — APPROVED** [review]
nice

**Review by burAQyilmaz — APPROVED** [review]
perfect

**Pull request merged**
